use_frameworks!

platform :ios, '8.0'

target 'SocketDemo_Example' do
  pod 'SocketDemo', :path => '../'

  pod 'CocoaAsyncSocket'
  
  target 'SocketDemo_Tests' do
    inherit! :search_paths

    
  end
end
